const StyleDictionary = require('style-dictionary');

const darkThemeOverrides = {
  'color-background-default': '#0a0a0a', // neutral.950
  'color-background-subtle': '#171717',  // neutral.900
  'color-background-overlay': '#000000', // neutral.950/pure black override
  'color-text-primary': '#fafafa',       // neutral.50
  'color-text-secondary': '#a3a3a3',     // neutral.400
  'color-text-disabled': '#525252',      // neutral.600
  'color-border-default': '#262626',     // neutral.800
  'color-border-strong': '#404040'       // neutral.700
};

// Register custom name transform to strip 'primitive'/'semantic'/'typography' and convert camelCase
StyleDictionary.registerTransform({
  name: 'name/custom/kebab',
  type: 'name',
  transformer: (token) => {
    let path = token.path.filter(segment => segment !== 'primitive' && segment !== 'semantic');
    
    // Strip "typography" category prefix to match CSS conventions like --font-size-* instead of --typography-font-size-*
    if (path[0] === 'typography') {
      path = path.slice(1);
    }
    
    return path
      .join('-')
      .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
      .toLowerCase();
  }
});

// Register custom formatter for dark mode overrides
StyleDictionary.registerFormat({
  name: 'css/variables-dark',
  formatter: function({ dictionary, options }) {
    const selector = options.selector || '[data-theme="dark"]';
    
    const variables = dictionary.allProperties.map(token => {
      const kebabName = token.name;
      const value = darkThemeOverrides[kebabName] || token.value;
      const comment = token.comment ? ` /* ${token.comment} */` : '';
      return `  --${kebabName}: ${value};${comment}`;
    }).join('\n');
    
    return `/**\n * Do not edit directly\n * Generated by Style Dictionary custom format\n */\n\n${selector} {\n${variables}\n}\n`;
  }
});

const filterNonPrimitives = (token) => {
  if (token.path[0] === 'color') {
    return token.path[1] === 'semantic';
  }
  return true;
};

module.exports = {
  source: ['tokens.json'],
  platforms: {
    css: {
      transforms: [
        'attribute/cti',
        'name/custom/kebab',
        'time/seconds',
        'content/icon',
        'size/rem',
        'color/css'
      ],
      buildPath: 'dist/',
      files: [{
        destination: 'tokens.css',
        format: 'css/variables',
        options: {
          selector: ':root',
          outputReferences: false
        },
        filter: filterNonPrimitives
      }]
    },
    cssDark: {
      transforms: [
        'attribute/cti',
        'name/custom/kebab',
        'time/seconds',
        'content/icon',
        'size/rem',
        'color/css'
      ],
      buildPath: 'dist/',
      files: [{
        destination: 'tokens.dark.css',
        format: 'css/variables-dark',
        options: {
          selector: '[data-theme="dark"]'
        },
        filter: (token) => {
          if (token.path[0] !== 'color' || token.path[1] !== 'semantic') {
            return false;
          }
          const kebabName = token.path.filter(segment => segment !== 'primitive' && segment !== 'semantic').join('-').toLowerCase();
          return Object.prototype.hasOwnProperty.call(darkThemeOverrides, kebabName);
        }
      }]
    }
  }
};
